import random
copypastas = [
    "!!HOLY FUCKING SHIT‼️‼️‼️‼️ IS THAT A MOTHERFUCKING BREAKING BAD REFERENCE??????!!!!!!!!!!11!1!1!1!1!1!1! 😱😱😱😱😱😱😱 WALTUH WHITE IS SO FUCKIGN COOL🔥🔥🔥🔥💯💯💯💯 🪨🪨 JESUS MARIE THEYRE MINERALS 🪨🪨 ⚗️⚗️YOU BOUGHT \
A METH LAB TO AN AIRPORT? ✈️ ✈️ OH ROOF PIZZA 🍕 ROOF PIZZA 🍕 ROOF PIZZ 🍕 🍕 ❗️I AM THE DANGER ❗️ I AM THE DANGER ❗️ I AM THE ONE WHO KNOCKS 🚪 ❗️Say my name! 🗣Say my name! 🗣❓ ❓ Say my name! 🗣Say my name! 🗣 Say my name! 🗣 Say! My name! 🗣 Saaaay my name 🗣 Youre the smaryerst guy i ever met..... 🧠 but ur too stopid to realize.. \
    the exact moment when walt whitman became woodrow wilson. OXYMANDIAD IS THE GREATEST EPISODE OF TEVELSION 📺 📺 👑 HANDS 🙌 DOWN⬇️. WE TRIED TO POISON ☠️ YOU, BECASE YOURE AN INSANE, DEGENRATE PEICE OF FILTH, AND YOU DESERVE TO DIE. WALT JR ASK FOR BREAKFAST HAHAHAH 🤣😂🤣🥲😂🤠🤠🤠👽👽😹😹😹. r/breakingbad r/bettercallsaul r/okbuddychicanery r/unexpected r/expectedthanos for balance r/sounding",
'I was poor so we had nothing but microwave shit and ramen. I didnt try broccoli until i was in jr high and i was so surprised at how good it tasted. My friends mom had made broccoli and cheese. I ate about 3 servings and told her how it was my first time to try it. I told them how cartoons always told me it would taste so bad. I wish i could have fucked my friends mom',
"I have never assaulted a cop nor would I but I have always maintained that if I ever had to run from one there isn’t a goddamn cop in America that would catch me especially with adrenaline going. I’m fast and shifty as shit. You also have to think like a wrestler and think 25 moves ahead. I’d be in the woods, climb a tree, pull some Jungle Book shit and start swinging, rip off a sleeve to leave my scent behind a rock, hop in a river, cover myself in mud, and crawl through a sewer like Shawshank Redemption. The one thing today that really makes it tough is so many people having cameras in their yards. There has never been a harder time to get away with crime than today.",
'Good afternoon, 47. Your target is Walter Hartwell White, on the surface a High School Chemistry Teacher and owner of a car wash. However, he has a second life where he goes by Heisenberg, and is one of the most notirious Meth Cooks in America. After getting his former boss Gustavo Fring killed, White built up a Meth Empire worth tens of millions of dollars, and has recently been expanded to Europe. Our client recently gained information that he non-fatally poisoned their child. Knowing this, they have turned to the ICA to have him dealt with. \
Happy hunting, 47.', 
"Stephen King Killed John Lennon \
Contrary to all reports about a lone drifter named Mark David Chapman who allegedly shot John Lennon in the back December 8, 1980 you’ll find ample evidence in the back issues of Time, Newsweek, and US News and World Report magazines to suggest otherwise. Namely, that John Lennon was, not only politically assassinated, but that Richard Nixon, Ronald Reagan and, you’d better sit down, horror novelist Stephen King are the three people who can be proven guilty of the crime. King being the real murderer and Chapman but a look-alike, paid actor misleading you with an absolute hoax, the media in tow. \
The evidence, specifically, is government codes in the bold print headlines of Time, Newsweek, and U.S. News and World Report magazines that were printed shortly before, during, and after the night of December 8, 1980. Hints in the headlines that you won’t find anywhere else that plug into John Lennon’s assassination with up to 70% frequency at times. These government codes, which read like gallows humor; “Thinking About John Lennon…Johnny Comes Marching Home…Kiss, Kiss, Bang, Bang, Ouch, Ouch…The Job Richard Nixon Really Wanted…Blasting the Opposition…America Needs A Poet Laureate…Maybe…Heeding Those Subtle Signs…Magazine Maze…All the Presidents Magazines…”. These codes include the killer’s face and true identity printed three and two months before the crime replete with headlines describing the then yet to come crime scene: “One Great Big Zippo Lighter…Perils of Pyrokinesis”. Pyrokinesis means fire and movement, and a man at night with a gun ablaze, crouched in a raincoat looks like a great big cigarette lighter. Subtle but dramatic codes. \
These crypto-codes include Mark David Chapman, the alleged name of the killer printed three weeks before the murder where Chapman writes that he is “…armed, a pawn, waiting to be moved into a hostile square…by the giant hand of Ronald Reagan…”. \
These government codes include dramatic photos of just elected Ronald Reagan sitting next to Richard Nixon’s book The Real War in Time and Newsweek issues released the day of the murder. In Time the bold headline above Reagan reads, “Who’s In? Who’s Out?” and below, ”Fitting Together the Pieces of a Complicated Jigsaw Puzzle…”\
That Richard Nixon tried to deport John Lennon in the 70’s is a known fact. John’s peace activism and lyrical barbs at “Tricky Dicky” and his perhaps-unparalleled worldwide appeal made John a target.\
Well, Inside The Real War several pages explain why “the prancing of the trendies…rock stars…beautiful people of New York…who say war is bad and peace is good…must be removed from the stage of public debate…by whatever means …a flyswatter…are needed…”. He even titles this philosophy, “The Nixon Doctrine”. Translation? Reagan’s In, Lennon’s Out. In fact “The Real John Lennon” and “The Real Richard Nixon” are two codes that precede the crime.\
Last, but certainly not least, according to identical matching photos of Stephen King attached to book reviews about Firestarter months before the assassination, the man photographed getting Lennon’s autograph hours before he killed him is not Mark Chapman like we were all told. Chapman’s glasses are the wrong prescription, his features are more centrally boxed in the middle of his face and his hair is the wrong texture, as well as the fact that the killer has dimples that Chapman does not. Only Stephen King’s features exactly trace the proportions of the autograph hound. Chapman is a look alike actor.\
This was the last coded evidence puzzle piece that I found, not knowing then who Stephen King was. This was back in 1982, my first clues being the “Who’s In? Who’s Out?” headlines above Reagan months earlier. I turned to my library then utterly convinced that the government had killed John Lennon based on the news clipping that appeared in June of 1982, a year and a half after the crime, where Chapman pleaded guilty two days before his trial and was sentenced to 20 years to life. Buried in a tiny corner of the back section, I knew a cover-up was at work. It was several weeks later while trying to find magazines that carried the murder report that I literally stumbled onto these codes.\
Now I was confronted, months later, with who actually pulled the trigger: famous author Stephen King?!?! Too much to believe? Beyond comprehension? Over all our heads? Is Nixon that tricky? Well, buckle up good readers, Stephen King writes all about it beginning with Salem’s Lot, five years before the crime, where he writes about shooting a man in the shoulder blades, stalking a politician with a gun in The Dead Zone, Johnny being the main character. He even writes about “…the fellow who killed John Lennon” in, I believe, three books. He practically confesses in his 1983 Playboy interview. He has even admitted to me, in his own handwriting, that I “…haven’t got the whole story yet…” and in a subsequent letter, signed Stephen King, he throws in a veiled bribe if I’d quit exposing this.",
"Band kids are cringe asf bruh y'all think y'all cool or some shit but just lame asf. Bitch ass lame ass good for nayfin bitches, fucking sad. I stole This phone just to tell yall shit y'all ain't believe. Finna live in ur moms basement for the rest of yo life. Fat as shit 300 pound fat asses blowing a fucking peice of metal like that takes skill. God damn. Can't even respond to me either I have it back to it’s owner 😭😭😭😭😭😭😭😭😭😭😭😭😭",
"ATTENTION CITIZEN! 市民请注意! \
This is the Central Intelligentsia of the Chinese Communist Party. 您的 Internet 浏览器历史记录和活动引起了我们的注意 YOUR INTERNET ACTIVITY HAS ATTRACTED OUR ATTENTION. 志們注意了 you have been found protesting in the subreddit!!!!! 這是通知你，你必須 我們將接管台灣 serious crime 以及世界其他地方 100 social credits have been deducted from your account 這對我們所有未來的下屬來說都是一個重要的機會 stop the protest immediately 立即加入我們的宣傳活動，提前獲得 do not do this again! 不要再这样做! if you do not hesitate, more social credits ( -11115 social credits )will be subtracted from your profile, resulting in the subtraction of ration supplies. (由人民供应部重新分配 ccp) you'll also be sent into a re-education camp in the xinjiang uyghur autonomous zone. \
为党争光! Glory to the CCP!"
]

copyran = random.choice(copypastas)